apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-nginx-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-nginx-hello-world
  template:
    metadata:
      labels:
        app: docker-nginx-hello-world
    spec:
      containers:
        - name: docker-nginx-hello-world
          image: dockerbogo/docker-nginx-hello-world
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: docker-nginx-hello-world
spec:
  selector:
    app: docker-nginx-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer