apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-nginx-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-nginx-hello-world
  template:
    metadata:
      labels:
        app: docker-nginx-hello-world
    spec:
      containers:
        - name: docker-nginx-hello-world
          image: dockerbogo/docker-nginx-hello-world
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: docker-nginx-hello-world
spec:
  selector:
    app: docker-nginx-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-nginx-hello-world
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-nginx-hello-world
                port:
                  number: 80